# Generated by Django 5.2.5 on 2025-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
